dist: trusty

group: deprecated-2017Q2

language: python

python: "3.6"

sudo: false

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
# command to run tests
script:
- py.test -vv tests/test_replicate.py
