dist: xenial

group: deprecated-2017Q2

language: python

python: "3.6"

sudo: false

cache: pip

before_install:
  # pip 20.3 gets stuck in an endless dependency resolution loop
  - pip install --upgrade 'pip<20.3'

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
- py.test -vv -s tests
