language: python
dist: xenial
python:
- 3.6

install:
- curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
  | python -
- source $HOME/.poetry/env
- which poetry
- poetry install -vv
- poetry show

script:
- poetry run pytest -vv ./tests
