# run with 
# g3k runjob aws-bucket-sync \
# GDC_BUCKET_NAME a_bucket_name \
# CHUNK_SIZE chunk_size \
# MANIFEST manifest_file \
# THREAD_NUM number of threads \
# LOG_BUCKET log buckets
# 
# HOW TO RUN
# Ex. gen3 runjob jobs/aws-bucket-replicate-job.yaml GDC_BUCKET_NAME testqueue2018 MANIFEST_S3 s3://giang816test/manifest_random THREAD_NUM 100 LOG_BUCKET xssxs CHUNK_SIZE 50
apiVersion: batch/v1
kind: Job
metadata:
  name: aws-bucket-replicate
spec:
  # not yet supported - backOffLimit: 3
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      volumes:
        - name: cred-volume
          secret:
            secretName: "aws-creds-secret"
        - name: project-acl-volume
          configMap:
            name: project-acl-manifest
        - name: creds-json-volume
          secret:
            secretName: "dcf-dataservice-json-secret"
      containers:
      - name: awsreplicate
        image: quay.io/cdis/dcf-dataservice:master
        imagePullPolicy: Always
        env:
          - name: GDC_BUCKET_NAME
            GEN3_GDC_BUCKET_NAME
          - name: LOG_BUCKET
            GEN3_LOG_BUCKET
          - name: CHUNK_SIZE
            GEN3_CHUNK_SIZE
          - name: THREAD_NUM
            GEN3_THREAD_NUM
          - name: MANIFEST_S3
            GEN3_MANIFEST_S3
        volumeMounts:
          - name: cred-volume
            mountPath: "/root/.aws/credentials"
            subPath: credentials
          - name: "project-acl-volume"
            mountPath: "/dcf-dataservice/GDC_datasets_access_control.csv"
            subPath: "GDC_datasets_access_control.csv"
          - name: "creds-json-volume"
            mountPath: "/secrets/dcf_dataservice_credentials.json"
            subPath: "dcf_dataservice_credentials.json"
        command: ["/bin/bash" ]
        args: 
          - "-c"
          - |
            echo """
            [default]
            region: us-east-1
            """ > ~/.aws/config
            python scripts/replicate.py aws_replicate --bucket $GDC_BUCKET_NAME --thread_num $THREAD_NUM --manifest_file $MANIFEST_S3 --global_config "{\"chunk_size\": $CHUNK_SIZE, \"log_bucket\": \"$LOG_BUCKET\"}"
            python scripts/replicate.py indexing  --thread_num 20 --manifest_file $MANIFEST_S3 --global_config "{\"chunk_size\": 3, \"log_bucket\": \"$LOG_BUCKET\"}"
      restartPolicy: Never
