# run with 
# Ex. gen3 runjob jobs/google-bucket-replicate-job.yaml PROJECT cdis-test-188416 MAX_WORKERS 4 RELEASE RS16 MANIFEST_FILE gs://data-flow-code/input/GDC_test.csv IGNORED_FILE gs://data-flow-code/ignored/ignored_files_manifest.csv LOG_BUCKET data-flow-code
apiVersion: batch/v1
kind: Job
metadata:
  name: google-bucket-replicate
spec:
  # not yet supported - backOffLimit: 3
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      volumes:
        - name: cred-volume
          secret:
            secretName: "google-creds-secret"
        - name: setting-volume
          secret:
            secretName: "dcf-dataservice-settings-secrets"
        - name: creds-json-volume
          secret:
            secretName: "dcf-dataservice-json-secret"
      containers:
      - name: googlereplicate
        image: quay.io/cdis/dcf-dataservice:master
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
        imagePullPolicy: Always
        env:
          - name: PROJECT
            GEN3_PROJECT
          - name: MAX_WORKERS
            GEN3_MAX_WORKERS
          - name: RELEASE
            GEN3_RELEASE
          - name: MANIFEST_FILE
            GEN3_MANIFEST_FILE
          - name: IGNORED_FILE
            GEN3_IGNORED_FILE
          - name: LOG_BUCKET
            GEN3_LOG_BUCKET
        volumeMounts:
          - name: cred-volume
            mountPath: "/secrets/google_service_account_creds"
            subPath: google_service_account_creds
          - name: "setting-volume"
            mountPath: "/secrets/dcf_dataservice_settings"
            subPath: "dcf_dataservice_settings"
          - name: "creds-json-volume"
            mountPath: "/secrets/dcf_dataservice_credentials.json"
            subPath: "dcf_dataservice_credentials.json"
        command: ["/bin/bash" ]
        args: 
          - "-c"
          - |
            cat /secrets/dcf_dataservice_settings > ./scripts/settings.py
            gcloud auth activate-service-account --key-file=/secrets/google_service_account_creds
            export GOOGLE_APPLICATION_CREDENTIALS=/secrets/google_service_account_creds
            gsutil cp $IGNORED_FILE /dcf-dataservice/ignored_files_manifest.csv
            python dataflow_pipeline.py  --runner DataflowRunner --project $PROJECT --job_name dcf-dataservice --autoscaling_algorithm NONE --num_worker $MAX_WORKERS --maxNumWorkers $MAX_WORKERS --staging_location gs://$LOG_BUCKET/$RELEASE/staging --temp_location gs://$LOG_BUCKET/$RELEASE/temp --output gs://$LOG_BUCKET/$RELEASE/output/ --setup_file ./setup.py --input $MANIFEST_FILE --extra_package indexclient-1.5.9.zip
      restartPolicy: Never
