# run with 
# Ex. gen3 runjob jobs/replicate-validation-job.yaml THREAD_NUM 4 MANIFEST_FILE gs://data-flow-code/input/manifest_big_head OUTPUT_MANIFEST gs://data-flow-code/out_manifest.csv
apiVersion: batch/v1
kind: Job
metadata:
  name: replicate-validation
spec:
  # not yet supported - backOffLimit: 3
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      volumes:
        - name: cred-volume
          secret:
            secretName: "google-creds-secret"
        - name: setting-volume
          secret:
            secretName: "dcf-dataservice-settings-secrets"
        - name: creds-json-volume
          secret:
            secretName: "dcf-dataservice-json-secret"
      containers:
      - name: googlereplicate
        image: quay.io/cdis/dcf-dataservice:master
        imagePullPolicy: Always
        resources:
          limits:
            memory: "16Gi"
          requests:
            cpu: "3"
            memory: "4Gi"
        env:
          - name: THREAD_NUM
            GEN3_THREAD_NUM
          - name: MANIFEST_FILE
            GEN3_MANIFEST_FILE
          - name: OUTPUT_MANIFEST
            GEN3_OUTPUT_MANIFEST
        volumeMounts:
          - name: cred-volume
            mountPath: "/secrets/google_service_account_creds"
            subPath: google_service_account_creds
          - name: "setting-volume"
            mountPath: "/secrets/dcf_dataservice_settings"
            subPath: "dcf_dataservice_settings"
          - name: "creds-json-volume"
            mountPath: "/secrets/dcf_dataservice_credentials.json"
            subPath: "dcf_dataservice_credentials.json"
        command: ["/bin/bash" ]
        args:
          - "-c"
          - |
            cat /secrets/dcf_dataservice_settings > ./scripts/settings.py
            gcloud auth activate-service-account --key-file=/secrets/google_service_account_creds
            export GOOGLE_APPLICATION_CREDENTIALS=/secrets/google_service_account_creds
            gsutil cp $IGNORED_FILE /dcf-dataservice/ignored_files_manifest.csv
            python scripts/replicate.py validate --thread_num $THREAD_NUM --manifest_file $MANIFEST_FILE --global_config "{}" --out_manifest $OUTPUT_MANIFEST

      restartPolicy: Never
